spring.application.name=EmailProject

#email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tabc1196@gmail.com
spring.mail.password=izcnokjedxvrulyt

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Enable multipart upload
spring.servlet.multipart.enabled=true

# Max file size
spring.servlet.multipart.max-file-size=10MB

# Max request size
spring.servlet.multipart.max-request-size=10MB
